"use client";

import { useState } from "react";
import {
  Lock,
  Sparkles,
  ChevronLeft,
  ChevronRight,
  AlertTriangle,
  CheckCircle2,
  TrendingUp,
  TrendingDown,
  BookOpen,
  Clock,
  Zap,
  FileSearch,
  ShieldCheck,
  MessageSquare,
} from "lucide-react";
import { motion, AnimatePresence } from "framer-motion";
import { cn } from "@/lib/utils";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { findGlossaryEntry } from "@/lib/glossary";
import type { ChecklistItem, Finding, Query } from "@/lib/types";

interface AIPanelProps {
  isAutoEnabled: boolean;
  selectedItem: ChecklistItem | null;
  findings: Finding[];
  queries: Query[];
  onActivateAuto: () => void;
  collapsed: boolean;
  onToggleCollapse: () => void;
}

const mockFindings: Finding[] = [
  {
    id: "fi1",
    auditId: "a2",
    title: "Related party acquisition below market value",
    description:
      "Property at 42 Elm Street acquired from Acme Holdings Pty Ltd for $620,000, below the independent valuation of $650,000.",
    severity: "high",
    sisReference: "s66",
    status: "confirmed",
    autoGenerated: true,
    createdAt: "2025-08-19T09:00:00Z",
  },
  {
    id: "fi2",
    auditId: "a2",
    title: "Dividend income reconciliation variance",
    description:
      "Variance of $12.50 between general ledger dividend income and CommSec holdings statement remains unresolved.",
    severity: "low",
    sisReference: "ASA200",
    status: "draft",
    autoGenerated: true,
    createdAt: "2025-08-20T10:00:00Z",
  },
];

const mockDraftedQueries = [
  {
    id: "dq1",
    subject: "Confirm franking credits on BHP dividends",
    body: "Could you please confirm the franking credits received on the BHP dividend payment dated 15 March 2025?",
  },
  {
    id: "dq2",
    subject: "Insurance premium allocation to members",
    body: "The fund appears to have insurance premiums that are not allocated to individual member accounts. Can you clarify?",
  },
];

const mockYoYComparisons = [
  {
    label: "Total fund assets",
    current: "$1,245,890",
    prior: "$1,102,340",
    change: "+13.0%",
    direction: "up" as const,
  },
  {
    label: "Contributions received",
    current: "$54,000",
    prior: "$50,000",
    change: "+8.0%",
    direction: "up" as const,
  },
  {
    label: "Benefits paid",
    current: "$0",
    prior: "$25,000",
    change: "-100%",
    direction: "down" as const,
  },
];

const severityColours: Record<string, string> = {
  low: "bg-amber/10 text-amber border-amber/20",
  medium: "bg-amber/15 text-amber-dark border-amber/30",
  high: "bg-rose/10 text-rose border-rose/20",
  critical: "bg-rose/15 text-rose-dark border-rose/30",
};

export function AIPanel({
  isAutoEnabled,
  selectedItem,
  findings,
  queries,
  onActivateAuto,
  collapsed,
  onToggleCollapse,
}: AIPanelProps) {
  const glossary = selectedItem
    ? findGlossaryEntry(selectedItem.sisReference)
    : null;

  return (
    <div
      className={cn(
        "relative flex h-full flex-col border-l border-[var(--border)] bg-paper transition-all duration-300",
        collapsed ? "w-0 overflow-hidden" : "w-[380px]"
      )}
    >
      {/* Collapse toggle */}
      <button
        onClick={onToggleCollapse}
        className="absolute -left-3 top-4 z-10 flex h-6 w-6 items-center justify-center rounded-full border border-[var(--border)] bg-white shadow-sm transition-colors hover:bg-cream"
      >
        {collapsed ? (
          <ChevronLeft className="h-3.5 w-3.5" />
        ) : (
          <ChevronRight className="h-3.5 w-3.5" />
        )}
      </button>

      {!collapsed && (
        <div className="flex h-full flex-col overflow-auto">
          {/* Header */}
          <div className="border-b border-[var(--border)] px-4 py-3">
            <div className="flex items-center gap-2">
              <Sparkles className="h-4 w-4 text-gold" />
              <span className="text-sm font-semibold text-ink">
                AuditHub Auto
              </span>
              {isAutoEnabled ? (
                <Badge variant="pass" dot>
                  Active
                </Badge>
              ) : (
                <Badge variant="na">Off</Badge>
              )}
            </div>
          </div>

          {/* Main content */}
          <div className="flex-1 overflow-auto">
            <AnimatePresence mode="wait">
              {!isAutoEnabled ? (
                <motion.div
                  key="auto-off"
                  initial={{ opacity: 0 }}
                  animate={{ opacity: 1 }}
                  exit={{ opacity: 0 }}
                  className="p-4"
                >
                  {/* Locked state */}
                  <div className="mb-4 flex flex-col items-center rounded-xl border border-[var(--border)] bg-cream/50 p-6 text-center">
                    <Lock className="mb-3 h-8 w-8 text-muted-foreground/40" />
                    <p className="font-serif text-sm font-semibold text-ink">
                      Auto is not enabled
                    </p>
                    <p className="mt-1 text-xs text-muted-foreground">
                      Activate to automate checklist items, draft queries, and
                      surface findings.
                    </p>
                  </div>

                  {/* What Auto would do */}
                  <div className="mb-4">
                    <p className="mb-2 text-xs font-semibold uppercase tracking-wider text-muted-foreground">
                      What Auto would do
                    </p>
                    <ul className="space-y-2">
                      {[
                        {
                          icon: Zap,
                          text: "Complete ~42 of 71 checklist items automatically",
                        },
                        {
                          icon: FileSearch,
                          text: "Extract and classify all uploaded documents",
                        },
                        {
                          icon: ShieldCheck,
                          text: "Surface compliance findings with SIS references",
                        },
                        {
                          icon: MessageSquare,
                          text: "Draft accountant queries for your review",
                        },
                      ].map((item, i) => (
                        <li key={i} className="flex items-start gap-2.5">
                          <item.icon className="mt-0.5 h-4 w-4 shrink-0 text-gold" />
                          <span className="text-sm text-ink">{item.text}</span>
                        </li>
                      ))}
                    </ul>
                  </div>

                  {/* Pricing */}
                  <div className="rounded-xl border border-gold/30 bg-gold/5 p-4 text-center">
                    <Badge
                      variant="auto"
                      className="mb-2"
                    >
                      First fund free
                    </Badge>
                    <p className="font-serif text-3xl font-bold text-ink">
                      $49
                    </p>
                    <p className="mt-0.5 text-xs text-muted-foreground">
                      per audit &middot; charged only at sign-off
                    </p>
                    <Button
                      variant="gold"
                      className="mt-3 w-full"
                      onClick={onActivateAuto}
                    >
                      <Sparkles className="mr-1.5 h-4 w-4" />
                      Activate Auto
                    </Button>
                  </div>
                </motion.div>
              ) : (
                <motion.div
                  key="auto-on"
                  initial={{ opacity: 0 }}
                  animate={{ opacity: 1 }}
                  exit={{ opacity: 0 }}
                  className="space-y-4 p-4"
                >
                  {/* Findings */}
                  <div>
                    <p className="mb-2 text-xs font-semibold uppercase tracking-wider text-muted-foreground">
                      Findings ({mockFindings.length})
                    </p>
                    <div className="space-y-2">
                      {mockFindings.map((finding) => (
                        <div
                          key={finding.id}
                          className="rounded-lg border border-[var(--border)] bg-white p-3"
                        >
                          <div className="mb-1 flex items-start gap-2">
                            <AlertTriangle className="mt-0.5 h-4 w-4 shrink-0 text-rose" />
                            <div className="min-w-0 flex-1">
                              <p className="text-sm font-medium leading-snug text-ink">
                                {finding.title}
                              </p>
                              <div className="mt-1 flex items-center gap-2">
                                <span
                                  className={cn(
                                    "rounded-full border px-2 py-0.5 text-[10px] font-medium",
                                    severityColours[finding.severity]
                                  )}
                                >
                                  {finding.severity}
                                </span>
                                <span className="font-mono text-[10px] text-muted-foreground">
                                  {finding.sisReference}
                                </span>
                              </div>
                            </div>
                          </div>
                        </div>
                      ))}
                    </div>
                  </div>

                  {/* Drafted queries */}
                  <div>
                    <p className="mb-2 text-xs font-semibold uppercase tracking-wider text-muted-foreground">
                      Drafted Queries ({mockDraftedQueries.length})
                    </p>
                    <div className="space-y-2">
                      {mockDraftedQueries.map((q) => (
                        <div
                          key={q.id}
                          className="rounded-lg border border-[var(--border)] bg-white p-3"
                        >
                          <p className="text-sm font-medium text-ink">
                            {q.subject}
                          </p>
                          <p className="mt-1 line-clamp-2 text-xs text-muted-foreground">
                            {q.body}
                          </p>
                          <div className="mt-2 flex gap-2">
                            <Button size="sm" variant="secondary">
                              Edit
                            </Button>
                            <Button
                              size="sm"
                              onClick={() => {}}
                            >
                              Accept
                            </Button>
                          </div>
                        </div>
                      ))}
                    </div>
                  </div>

                  {/* Year-over-year comparison */}
                  <div>
                    <p className="mb-2 text-xs font-semibold uppercase tracking-wider text-muted-foreground">
                      Year-over-Year Comparison
                    </p>
                    <div className="space-y-2">
                      {mockYoYComparisons.map((comp) => (
                        <div
                          key={comp.label}
                          className="rounded-lg border border-[var(--border)] bg-white p-3"
                        >
                          <p className="text-xs text-muted-foreground">
                            {comp.label}
                          </p>
                          <div className="mt-1 flex items-end justify-between">
                            <span className="text-lg font-semibold text-ink">
                              {comp.current}
                            </span>
                            <div className="flex items-center gap-1 text-xs">
                              {comp.direction === "up" ? (
                                <TrendingUp className="h-3 w-3 text-forest" />
                              ) : (
                                <TrendingDown className="h-3 w-3 text-rose" />
                              )}
                              <span
                                className={cn(
                                  comp.direction === "up"
                                    ? "text-forest"
                                    : "text-rose"
                                )}
                              >
                                {comp.change}
                              </span>
                              <span className="text-muted-foreground">
                                from {comp.prior}
                              </span>
                            </div>
                          </div>
                        </div>
                      ))}
                    </div>
                  </div>
                </motion.div>
              )}
            </AnimatePresence>
          </div>

          {/* Bottom section (always visible) */}
          <div className="border-t border-[var(--border)] bg-cream/50">
            {/* Glossary box */}
            {selectedItem && (
              <div className="border-b border-[var(--border)] p-4">
                <div className="mb-1.5 flex items-center gap-1.5">
                  <BookOpen className="h-3.5 w-3.5 text-muted-foreground" />
                  <span className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">
                    Glossary
                  </span>
                </div>
                {glossary ? (
                  <div>
                    <p className="text-sm font-medium text-ink">
                      {glossary.term}
                    </p>
                    <p className="mt-1 text-xs leading-relaxed text-muted-foreground">
                      {glossary.definition.slice(0, 200)}
                      {glossary.definition.length > 200 ? "..." : ""}
                    </p>
                  </div>
                ) : (
                  <p className="text-xs text-muted-foreground">
                    No glossary entry for {selectedItem.sisReference}
                  </p>
                )}
              </div>
            )}

            {/* History box */}
            <div className="p-4">
              <div className="mb-1.5 flex items-center gap-1.5">
                <Clock className="h-3.5 w-3.5 text-muted-foreground" />
                <span className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">
                  Last Year
                </span>
              </div>
              {selectedItem ? (
                <div className="flex items-center gap-2">
                  <CheckCircle2 className="h-4 w-4 text-forest" />
                  <span className="text-sm text-ink">
                    Passed &mdash; FY24 audit
                  </span>
                </div>
              ) : (
                <p className="text-xs text-muted-foreground">
                  Select an item to view prior year decision
                </p>
              )}
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
