export type AuditStatus = 'not_started' | 'in_progress' | 'awaiting_accountant' | 'review' | 'signed';
export type ChecklistStatus = 'pass' | 'fail' | 'query' | 'na' | 'todo' | 'auto';
export type FindingSeverity = 'low' | 'medium' | 'high' | 'critical';
export type QueryStatus = 'draft' | 'sent' | 'responded' | 'resolved';
export type DocumentClassification = 'trust_deed' | 'financial_statements' | 'bank_statement' | 'investment_report' | 'member_statement' | 'tax_return' | 'rollover' | 'insurance' | 'minutes' | 'other';

export interface Fund {
  id: string;
  name: string;
  abn: string;
  structure: 'individual' | 'corporate' | 'individual_corporate';
  trusteeNames: string[];
  accountantName: string;
  accountantEmail: string;
  accountantFirm: string;
  yearEndDate: string;
  createdAt: string;
}

export interface Audit {
  id: string;
  fundId: string;
  fundName: string;
  fundAbn: string;
  year: number;
  status: AuditStatus;
  progress: number;
  queriesOpen: number;
  autoEnabled: boolean;
  autoItemsCompleted: number;
  totalItems: number;
  completedItems: number;
  owner: string;
  ownerAvatar?: string;
  lastActivity: string;
  yearEndDate: string;
  daysInStatus: number;
  findingsCount: number;
  documentsCount: number;
  timeSavedMinutes: number;
  createdAt: string;
  updatedAt: string;
}

export interface ChecklistItem {
  id: string;
  auditId: string;
  phase: string;
  phaseLabel: string;
  section: string;
  questionText: string;
  status: ChecklistStatus;
  sisReference: string;
  lastChanged: string;
  autoCompleted: boolean;
  autoConfidence?: number;
  notes: string;
  evidenceIds: string[];
  queryId?: string;
  findingId?: string;
  order: number;
}

export interface AuditDocument {
  id: string;
  auditId: string;
  filename: string;
  classification?: DocumentClassification;
  classificationLabel?: string;
  uploadedAt: string;
  thumbnailUrl?: string;
  autoClassified: boolean;
  confidence?: number;
  extractedFields?: ExtractedField[];
  pageCount: number;
  fileSize: number;
}

export interface ExtractedField {
  id: string;
  label: string;
  value: string;
  confidence: number;
  confirmed: boolean;
  boundingBox?: { page: number; x: number; y: number; w: number; h: number };
}

export interface Finding {
  id: string;
  auditId: string;
  title: string;
  description: string;
  severity: FindingSeverity;
  sisReference: string;
  status: 'draft' | 'confirmed' | 'resolved';
  autoGenerated: boolean;
  createdAt: string;
}

export interface Query {
  id: string;
  auditId: string;
  checklistItemId?: string;
  subject: string;
  body: string;
  status: QueryStatus;
  accountantName: string;
  accountantEmail: string;
  raisedAt: string;
  respondedAt?: string;
  messages: QueryMessage[];
}

export interface QueryMessage {
  id: string;
  from: string;
  fromRole: 'auditor' | 'accountant';
  body: string;
  timestamp: string;
  attachments?: string[];
}

export interface ActivityEvent {
  id: string;
  type: 'status_change' | 'query_sent' | 'query_replied' | 'document_uploaded' | 'auto_completed' | 'finding_raised' | 'audit_signed' | 'note_added' | 'item_reviewed';
  actor: string;
  actorInitials: string;
  description: string;
  timestamp: string;
  auditId?: string;
  fundName?: string;
}

export interface DashboardStats {
  fundsInAudit: number;
  signedThisFY: number;
  timeSavedHours: number;
  planTier: string;
  fundsInAuditTrend: number[];
  signedTrend: number[];
  timeSavedTrend: number[];
}

export interface SavedView {
  id: string;
  name: string;
  filters: Record<string, string | boolean>;
  isDefault?: boolean;
  icon?: string;
}

export interface User {
  id: string;
  email: string;
  name: string;
  firmName: string;
  asicNumber: string;
  avatar?: string;
  role: 'admin' | 'auditor' | 'reviewer';
}

export interface Firm {
  id: string;
  name: string;
  abn: string;
  address: string;
  letterheadUrl?: string;
  members: User[];
}

export interface GlossaryEntry {
  term: string;
  reference: string;
  definition: string;
  atoLink: string;
  relatedItems: string[];
}

export interface TourStep {
  id: string;
  targetSelector: string;
  title: string;
  description: string;
  position: 'top' | 'bottom' | 'left' | 'right';
}
